### ISSUE TITLE
添加的样例路由会导致route:cache报错

### ISSUE THREAD

**Issue by nickfan** [douyasi/laravel-wang-editor#1]
添加的样例路由会导致route:cache报错

**Comment by ycrao** [comment]
请贴出出错的图片或者日志。

**Comment by nickfan** [comment]
<img width="550" alt="qq20161114-0 2x" src="https://cloud.githubusercontent.com/assets/100613/20258368/4b4c3502-aa8a-11e6-8691-bc4966969f99.png">

版本 laravel 5.1

```
  [LogicException]
  Unable to prepare route [laravel-wang-editor/example] for serialization. Us
  es Closure.
```

建议只写controller，路由啥的还是在文档里写例子好了。
不然大家都只能像我一样fork以后自己关掉再用了。

**Comment by ycrao** [comment]
感谢您的回报，这是无法缓存闭包路由造成的，稍后版本会修正为调用控制器方法
