### ISSUE TITLE
上传路径 可配置

### ISSUE THREAD

**Issue by dryyun** [douyasi/laravel-wang-editor#2]
上传基本路径（uploads/content/），上传路径（/ yymmdd | yymm |yyyy |../）等，是不是写到 配置文件里，做成可配置比较好 ？
现在是在代码里写死的。。

**Comment by ycrao** [comment]
@dryyun 这是太过于细节化的需求，现在你是这种需求，没准下个人过来说，我要随机目录（文件）名。关于图片上传，其实您完全可以参考本包示例代码，结合自己的实际需求，重写一个，然后在 `wang-editor.php` 里添加进去您的 `uploadImgUrl` 路由地址。相信，这花费不了你多少时间。

**Comment by dryyun** [comment]
@ycrao  恩，的确可以这么解决，自定义 upload 路由，抱歉是我没有把代码看完全。
