### ISSUE TITLE
laravel5.1中上传图片问题

### ISSUE THREAD

**Issue by 2fa202603** [douyasi/laravel-wang-editor#3]
在helpers.php中修改102行，
```
_{$editor_id}.config.uploadParams = {
        token : '{$token}'
};
```
为：
```
_{$editor_id}.config.uploadParams = {
        _token : '{$token}'
};
```

这样可以正常上传图片，不过也可能有别的解决办法。

**Comment by ycrao** [comment]
@wangjialinbeijing `5.1` 版本我没有测试，不知道你有没有对 `5.2+` 测试过，如果有的版本行，有的版本不行，我考虑做成配置项。

**Comment by wxuns** [comment]
我能不能问一下这个怎么配置菜单栏的内容，第一次接触wangEditor有点下不去手

**Comment by XHXHXHX** [comment]
wangEditor提示: 使用返回的结果获取图片，发生错误。请确认以下结果是否正确：/uploads/content/20171213/5a308e3d25449_41o.png<link rel='stylesheet' type='text/css' property='stylesheet' href='//www.fbltech.cn/_debugbar/assets/stylesheets?v=1505741566'><script type='text/javascript' src='//www.fbltech.cn/_debugbar/assets/javascript?v=1505741566'></script><script type="text/javascript">jQuery.noConflict(true);</script>

**Comment by ycrao** [comment]
@XHXHXHX 你是不是开启 laravel-debug-bar插件，有2个jquery版本可能存在影响，建议关闭之后试试。

**Comment by 2fa202603** [comment]
font{
        line-height: 1.7;
    }
    ul,ol{
        list-style-position: inside;
    }


    
收到，我试一试，感谢答复！



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                



    在2017年12月13日 14:55，飞扬<notifications@github.com> 写道： 


@XHXHXHX 你是不是开启 laravel-debug-bar插件，有2个jquery版本可能存在影响，建议关闭之后试试。
