### ISSUE TITLE
不支持图片粘贴

### ISSUE THREAD

**Issue by cyhano** [douyasi/laravel-wang-editor#8]
比如用截图软件把截图复制到剪贴板，不能往编辑器里面粘贴

**Comment by ycrao** [comment]
我并不是 [wangEditor](http://www.wangeditor.com/) 编辑器的开发者，你可以向原作者 [wangfupeng1988/wangEditor](https://github.com/wangfupeng1988/wangEditor/) 提出 issues，目前该编辑器支持拖曳上传，当然如果可以，你可以尝试使用 [laravel-ckeditor](https://github.com/douyasi/laravel-ckeditor)，它支持三种上传方式。
